DROP SCHEMA IF EXISTS   INCAR_PROTOCOL;
CREATE SCHEMA INCAR_PROTOCOL;
USE INCAR_PROTOCOL;
#协议供应商
CREATE TABLE T_SUPPLIER(
  ID INT AUTO_INCREMENT COMMENT           '主键自动增长',
  NAME VARCHAR(50) NOT NULL COMMENT       '供应商名称',
  DETAIL VARCHAR(500) COMMENT             '供应商介绍',
  PRIMARY KEY (ID)
);
#协议表
CREATE TABLE T_PROTOCOL(
  ID INT AUTO_INCREMENT COMMENT           '主键自动增长',
  NAME VARCHAR(50) NOT NULL COMMENT       '协议名称',
  DETAIL VARCHAR(500) COMMENT             '协议详情',
  PROTOCOL_TYPE INT DEFAULT 0 COMMENT     '协议类型 0:上行协议(终端-->服务器) 1:下行协议(服务器-->终端)', 
  SUPPLIER_ID INT COMMENT                 '供应商ID',
  PRIMARY KEY (ID)
);
#协议条目关系表
CREATE TABLE T_PROTOCOL_ELEMENT(
  ID INT AUTO_INCREMENT COMMENT           '主键自动增长',
  PROTOCOL_ID INT COMMENT                 '协议ID',
  ELEMENT_ID INT COMMENT                   '条目ID',
  ELEMENT_ORDER INT NOT NULL COMMENT       '条目在协议中的顺序,0开始',
  PRIMARY KEY (ID)
);
#协议条目表
CREATE TABLE T_ELEMENT(
  ID INT AUTO_INCREMENT COMMENT           '主键自动增长',
  NAME VARCHAR(50) COMMENT                '条目名称',
  BEAN_PROPERTY VARCHAR(100) COMMENT      '条目对应JavaBean属性名称',
  ELEMENT_TYPE INT NOT NULL COMMENT        '条目返回数据的类型,对应枚举类DataType',
  PARENT INT DEFAULT 0 COMMENT            '父条目ID,其指向的父条目必须是一个变长数组类型',
  GROUP_ORDER INT COMMENT                 '条目在父条目中的顺序,0开始',
  PRIMARY KEY (ID)
);
#外键关系
ALTER TABLE T_PROTOCOL ADD CONSTRAINT F_PROTOCOL_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES T_SUPPLIER(ID);
ALTER TABLE T_PROTOCOL_ELEMENT ADD CONSTRAINT F_PROTOCOL_ELEMENT_PROTOCOL FOREIGN KEY (PROTOCOL_ID) REFERENCES T_PROTOCOL(ID);
ALTER TABLE T_PROTOCOL_ELEMENT ADD CONSTRAINT F_PROTOCOL_ELEMENT_ELEMENT FOREIGN KEY (ELEMENT_ID) REFERENCES T_ELEMENT(ID);
ALTER TABLE T_ELEMENT ADD CONSTRAINT F_ELEMENT_PARENT FOREIGN KEY (PARENT) REFERENCES T_ELEMENT(ID);

#初始化数据
INSERT INTO T_SUPPLIER(NAME, DETAIL) VALUES ('蓝度','英卡车联网项目第一版终端供应商及协议供应商');

INSERT INTO T_PROTOCOL(NAME, DETAIL, PROTOCOL_TYPE, SUPPLIER_ID) VALUES ('1603','终端注册/激活协议',0,1);

